apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      serviceAccountName: go-micro
      containers:
        - name: server
          image: checkoutservice
          ports:
            - containerPort: 5050
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          env:
            - name: PORT
              value: "5050"
            - name: MICRO_REGISTRY_ADDRESS
              value: "kubernetes"
            - name: PRODUCTCATALOGSERVICE
              value: "productcatalogservice"
            - name: SHIPPINGSERVICE
              value: "shippingservice"
            - name: PAYMENTSERVICE
              value: "paymentservice"
            - name: EMAILSERVICE
              value: "emailservice"
            - name: CURRENCYSERVICE
              value: "currencyservice"
            - name: CARTSERVICE
              value: "cartservice"
            # - name: DISABLE_STATS
            #   value: "1"
            # - name: DISABLE_TRACING
            #   value: "1"
            # - name: DISABLE_PROFILER
            #   value: "1"
            # - name: JAEGER_SERVICE_ADDR
            #   value: "jaeger-collector:14268"
          # resources:
          #   requests:
          #     cpu: 100m
          #     memory: 64Mi
          #   limits:
          #     cpu: 200m
          #     memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
spec:
  type: ClusterIP
  selector:
    app: checkoutservice
  ports:
    - name: grpc
      port: 5050
      targetPort: 5050
